import Link from "@/components/marketing/public-link";
import { SiteShell, Breadcrumbs, SectionLabel, CTA, FAQ } from "@/components/marketing/site-shell";
import { publicMetadata } from "@/lib/marketing-seo";
export const metadata = publicMetadata("Google Play Integration: Listings, Locales & Reporting", "See what Sorted's Google Play integration supports: listing synchronization, reviewed text publishing, localization, and permission-dependent reporting.", "/integrations/google-play");
const capabilities = [
  ["Store listing context", "Supported", "Synchronize supported listing information for your connected app. Check imported details before using them as a source."],
  ["Listing text publishing", "Supported with access", "Send reviewed app titles, short descriptions, full descriptions, and selected locales. Google’s review and publishing settings still apply."],
  ["App quality reporting", "Permission-dependent", "Review available Google Play Developer Reporting data when the connected account has the required scope and app access."],
  ["Promotional event planning", "Supported in Sorted", "Prepare dates, copy, and creative briefs in the product calendar. Submit the event through Play Console."],
  ["Promotional performance", "Additional setup", "Available where report access has been configured. OAuth alone does not provide every Play Console report."],
  ["Direct event publishing", "Not currently supported", "Promotional content creation and submission remain a Play Console step."],
];
export default function GooglePlayPage() { return <SiteShell><div className="m-container"><Breadcrumbs items={[{ name: "Google Play integration" }]} /><section className="m-page-hero"><SectionLabel>YOUR STORE, CONNECTED</SectionLabel><h1>A shorter path<br />from draft to listing.</h1><p>Connect the Google account with access to your app. Bring listing work into Sorted, review it in context, and choose when to send supported changes back.</p></section><div className="m-table-wrap"><table className="m-status-table"><caption className="m-label" style={{ textAlign: "left", paddingBottom: 15 }}>CURRENT GOOGLE PLAY CAPABILITIES</caption><thead><tr><th scope="col">Workflow</th><th scope="col">Availability</th><th scope="col">What to expect</th></tr></thead><tbody>{capabilities.map(([name, status, text]) => <tr key={name}><th scope="row" style={{ background: "transparent", fontSize: 14 }}>{name}</th><td>{status}</td><td>{text}</td></tr>)}</tbody></table></div><section className="m-section m-prose m-prose-narrow"><h2>How to connect</h2><ol><li>Open your product in Sorted and go to its Google Play connection.</li><li>Sign in with a Google account that has the relevant app permissions in Play Console.</li><li>Confirm the Android package and review the information returned by the connection.</li><li>Review your listing draft, select the intended locales, and explicitly publish when ready.</li></ol><h2>What access means</h2><p>The connection uses Google authorization to request publishing and reporting access. The actions available depend on that account’s Play Console permissions. Review Google’s consent screen and connect only an account authorized for the app.</p><p>You can revoke access through your Google account’s third-party connections. For questions about your Sorted account or stored product data, <Link href="/contact">contact the founder</Link>. App connections, drafts, and product workspaces are not public marketing pages.</p><p>Sorted is independent software and is not endorsed by or affiliated with Google.</p></section></div><FAQ items={[["Does a successful request mean my listing is already live?", "Not necessarily. Google review, managed publishing, and the app's settings can affect visibility. Verify the final status and published result in Play Console."], ["Do I need my own Google Cloud OAuth project?", "The application's Google OAuth configuration is managed centrally by Sorted. You authorize your own Google account for your product. Some reporting workflows can require additional permissions or report setup."], ["Can I use Sorted without connecting Google Play?", "You can work with product context, drafts, and planning without publishing access. Synchronization and sending listing updates require an authorized connection."]]} /><CTA /></SiteShell>; }
