import Link from "@/components/marketing/public-link";
import { ArrowRight, ArrowUpRight, Check, Languages, CalendarDays, ScanText, MoveUpRight } from "lucide-react";
import { SiteShell, SectionLabel, CTA, FAQ, JsonLd, organization } from "@/components/marketing/site-shell";
import { ProductDemo } from "@/components/marketing/product-demo";
import { features, guides, homeFaqs, SITE_URL } from "@/lib/marketing-content";
import { publicMetadata } from "@/lib/marketing-seo";

export const metadata = publicMetadata("ASO & Organic Growth Workspace for Apps and Games", "Sorted connects Google Play ASO, listing localization, and promotional event planning in one workspace for mobile app and game teams.", "/");

export default function HomePage() {
  return <SiteShell>
    <JsonLd data={{ "@context": "https://schema.org", "@graph": [organization, { "@type": "WebSite", "@id": `${SITE_URL}/#website`, url: SITE_URL, name: "Sorted", alternateName: "Sort3d", publisher: { "@id": `${SITE_URL}/#organization` } }, { "@type": "SoftwareApplication", name: "Sorted", applicationCategory: "BusinessApplication", operatingSystem: "Web", url: SITE_URL, description: "An organic growth workspace for mobile apps and games, with Google Play ASO, listing localization, and promotional content planning.", publisher: { "@id": `${SITE_URL}/#organization` }, featureList: ["Google Play listing optimization", "Listing localization", "Product event calendars", "Human-reviewed AI drafts"] }] }} />
    <section className="m-container m-hero"><div className="m-hero-top"><div><SectionLabel>THE ORGANIC GROWTH WORKSPACE</SectionLabel><h1>Big ideas.<br />Better discovery.<br /><em>All sorted.</em></h1></div><div className="m-hero-copy"><span className="m-hero-spark" aria-hidden="true"><MoveUpRight size={44} strokeWidth={1.3} /></span><p>Your app deserves to be found. Bring Google Play ASO, localization, and promotional content into one thoughtful workflow.</p><div className="m-actions"><a className="m-button" href="/sign-up">Get started with Sorted <ArrowUpRight size={18} /></a><a className="m-text-link" href="#workspace-preview">Take a look inside <ArrowRight size={16} /></a></div><p className="m-hero-note"><span className="m-live-dot" /> Built for mobile app & game teams</p></div></div><div id="workspace-preview"><ProductDemo /></div></section>
    <section className="m-principle-strip"><div className="m-container"><p>Good growth work<br /><strong>stays connected.</strong></p><span><Check size={16} /> Product context first</span><span><Check size={16} /> Every draft editable</span><span><Check size={16} /> You choose what goes live</span></div></section>
    <section className="m-container m-section" id="product"><div className="m-section-heading"><div><SectionLabel number="01">FROM THE FIRST IMPRESSION TO THE NEXT EVENT</SectionLabel><h2>Your growth work.<br /><em>In a better place.</em></h2></div><p>Less time piecing things together.<br />More context for the next decision.</p></div><div className="m-feature-grid">{features.map((f, i) => { const Icon = [ScanText, Languages, CalendarDays][i]; return <Link className={`m-feature-card m-tone-${i}`} key={f.slug} href={`/features/${f.slug}`}><div className="m-feature-art" aria-hidden="true">{i === 0 ? <><span className="m-art-label">A CLEARER FIRST IMPRESSION</span><div className="m-art-listing"><span className="m-app-icon">d</span><div><strong>Daylight: Daily Habits</strong><span>Your product. Clearly expressed.</span></div><span className="m-art-check"><Check size={14} /></span></div><div className="m-art-lines"><i /><i /><i /></div></> : i === 1 ? <><span className="m-art-label">A MESSAGE THAT TRAVELS</span><div className="m-language-cloud"><span>Hello.</span><span>Hola.</span><span>Bonjour.</span><span lang="ar" dir="rtl">مرحبًا.</span></div></> : <><span className="m-art-label">EVERY MOMENT HAS A PLACE</span><div className="m-mini-calendar"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><strong>12</strong><strong>13</strong><strong>14</strong><strong>15</strong><strong>16</strong><div>Season launch <ArrowUpRight size={12} /></div></div></>}</div><div className="m-feature-card-copy"><span className="m-feature-category"><Icon size={15} /> {f.eyebrow}</span><h3>{["Make your listing worth a closer look.", "Go further, one locale at a time.", "Make the next launch feel organized."][i]}</h3><p>{["Turn product research into stronger store copy. Review the details and send approved updates to Google Play.", "Adapt your approved source copy into editable local listings. Keep the product promise consistent.", "Bring event dates, campaign copy, and creative briefs together in a calendar for each product."][i]}</p><span className="m-text-link">Explore {i === 0 ? "ASO" : i === 1 ? "localization" : "event planning"} <ArrowUpRight size={16} /></span></div></Link>; })}</div></section>
    <section className="m-workflow-section"><div className="m-container m-section"><div className="m-section-heading"><div><SectionLabel number="02">A SMALLER GAP BETWEEN THINKING AND DOING</SectionLabel><h2>Start with context.<br />Keep moving with purpose.</h2></div><p>A connected process, from the listing you have to the next change you can stand behind.</p></div><ol className="m-workflow">{[["Know the product", "Add your app, audience, and current listing. Give the work a reliable starting point."], ["Shape the next move", "Turn research into listing drafts, localizations, and product-specific event plans."], ["Review the details", "Edit the copy. Check the claims. Keep a person in charge of what gets approved."], ["Publish and learn", "Send supported listing updates, hand off event packages, and review available reporting."]].map(([title, text], i) => <li key={title}><span className="m-step-number">0{i + 1}<ArrowRight size={17} /></span><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
    <section className="m-container m-section m-integration"><div className="m-integration-art" aria-hidden="true"><span className="m-integration-node m-node-sorted">s.</span><span className="m-connection-line"><i /><i /><i /></span><span className="m-integration-node m-node-play"><svg viewBox="0 0 32 36" width="48" height="54"><path d="M2 2 30 18 2 34Z" fill="currentColor" /></svg></span><span className="m-connection-caption">YOUR PRODUCT → YOUR GOOGLE PLAY LISTING</span></div><div><SectionLabel>CONNECTED, WITH YOU IN CONTROL</SectionLabel><h2>Google Play.<br /><em>Part of the workflow.</em></h2><p>Bring supported listing details into Sorted and send reviewed text updates back. Your Google permissions and publishing settings stay part of the process.</p><Link className="m-text-link" href="/integrations/google-play">See exactly what connects <ArrowUpRight size={17} /></Link></div></section>
    <section className="m-container m-tool-teaser"><div><SectionLabel>A USEFUL PLACE TO START</SectionLabel><h2>Does your listing fit?</h2><p>Check your Google Play title and descriptions against the field limits. Free, in your browser, with no account required.</p><Link className="m-button" href="/tools/google-play-listing-checker">Check your listing <ArrowUpRight size={18} /></Link></div><div className="m-tool-limits" aria-label="Google Play character limits"><div><strong>30</strong><span>App name</span></div><div><strong>80</strong><span>Short description</span></div><div><strong>4,000</strong><span>Full description</span></div></div></section>
    <section className="m-container m-section"><div className="m-section-heading"><div><SectionLabel number="03">A LITTLE GUIDANCE GOES A LONG WAY</SectionLabel><h2>Make the next move<br />an informed one.</h2></div><Link className="m-text-link" href="/guides">All growth guides <ArrowUpRight size={17} /></Link></div><div className="m-guide-grid">{guides.map((g, i) => <Link className="m-guide-card" href={`/guides/${g.slug}`} key={g.slug}><div className={`m-guide-visual m-tone-${i}`} aria-hidden="true"><span>0{i + 1}</span><ArrowUpRight size={40} strokeWidth={1} /></div><SectionLabel>{g.category} · {g.minutes}</SectionLabel><h3>{g.title}</h3><p>{g.description}</p></Link>)}</div></section>
    <FAQ items={homeFaqs} /><CTA />
  </SiteShell>;
}
