"use client";
import { useState } from "react";
import { Copy, RotateCcw, WandSparkles } from "lucide-react";
import { checkListing, EMPTY_LISTING, LISTING_FIELDS, SAMPLE_LISTING, type ListingCopy } from "@/lib/listing-checker";
export function ListingChecker() {
  const [copy, setCopy] = useState<ListingCopy>(EMPTY_LISTING);
  const [notice, setNotice] = useState("");
  const result = checkListing(copy);
  function update(key: keyof ListingCopy, value: string) { setCopy(current => ({ ...current, [key]: value })); setNotice(""); }
  async function copyText() {
    try { await navigator.clipboard.writeText(LISTING_FIELDS.map(f => `${f.label}\n${copy[f.key]}`).join("\n\n")); setNotice("Listing copied to your clipboard."); }
    catch { setNotice("Clipboard access is unavailable. You can select and copy the text directly from the fields."); }
  }
  return <div className="m-checker"><div className="m-checker-fields">{result.fields.map(f => <div className="m-checker-field" key={f.key}><label htmlFor={`listing-${f.key}`}>{f.label}<span className={f.over ? "m-over" : ""}>{f.count.toLocaleString("en-US")} / {f.limit.toLocaleString("en-US")}</span></label>{f.key === "title" ? <input id={`listing-${f.key}`} value={copy[f.key]} onChange={e => update(f.key, e.target.value)} placeholder="Your app name" aria-invalid={f.over > 0} aria-describedby={`${f.key}-hint`} autoComplete="off" spellCheck /> : <textarea id={`listing-${f.key}`} data-long={f.key === "fullDescription"} value={copy[f.key]} onChange={e => update(f.key, e.target.value)} placeholder={f.key === "shortDescription" ? "The reason someone should care about your app" : "Explain the experience, features, and audience in your own words."} aria-invalid={f.over > 0} aria-describedby={`${f.key}-hint`} spellCheck />}<span id={`${f.key}-hint`} className={`m-field-message ${f.over ? "m-over" : ""}`}>{f.over ? `${f.over.toLocaleString("en-US")} over the limit. Edit the wording before publishing.` : `${(f.limit - f.count).toLocaleString("en-US")} remaining`}</span></div>)}<div className="m-checker-actions"><button className="m-button m-button-quiet" onClick={() => { setCopy({ ...SAMPLE_LISTING }); setNotice("Fictional Daylight example loaded."); }}><WandSparkles size={15} /> Load example</button><button className="m-button m-button-quiet" onClick={() => { setCopy({ ...EMPTY_LISTING }); setNotice("Fields cleared."); }}><RotateCcw size={15} /> Clear</button><button className="m-button" onClick={copyText}><Copy size={15} /> Copy listing</button></div><p role="status" className="m-checker-privacy">{notice}</p><p className="m-checker-privacy">This checker runs locally in your browser. It does not send or save your listing text, call an AI provider, or connect to Google Play. Leaving or reloading the page clears your draft.</p></div><aside className="m-checker-preview"><p className="m-label">A QUICK COPY PREVIEW</p><h2>See the story take shape.</h2><div className="m-store-preview"><span className="m-app-icon" aria-hidden="true">s</span><h3>{copy.title || "Your app name"}</h3><p>{copy.shortDescription || "Your short description appears here."}</p><small>About this app</small><p>{copy.fullDescription || "Your full description appears here."}</p></div><div className="m-checker-result" aria-live="polite"><strong>{result.withinLimits ? "All three fields fit the length limits." : !result.complete ? "Add all three fields to check a complete listing." : "Some text exceeds the field limits."}</strong>{result.notes.length > 0 && <ul>{result.notes.map(note => <li key={note}>{note}</li>)}</ul>}<p>Length checks are not an ASO score or Google policy approval. Counts use UTF-16 units, matching Sorted’s publishing validator; some symbols can count as more than one. Verify the final text in Play Console.</p></div></aside></div>;
}
