"use client";

import { useRef, useState } from "react";
import { Check, ChevronDown, LayoutGrid, CalendarDays, Languages, FileText, ArrowUpRight, Sparkles, CircleCheck, Search } from "lucide-react";

type Tab = "listing" | "localization" | "calendar";
const tabs: { id: Tab; label: string; icon: typeof FileText }[] = [{ id: "listing", label: "Store listing", icon: FileText }, { id: "localization", label: "Localization", icon: Languages }, { id: "calendar", label: "Event calendar", icon: CalendarDays }];

export function ProductDemo({ initialTab = "listing" }: { initialTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(initialTab);
  const buttons = useRef<(HTMLButtonElement | null)[]>([]);
  return <div className="m-demo-wrap"><div className="m-demo">
    <aside className="m-demo-rail" aria-hidden="true"><span className="m-mini-mark">s.</span><LayoutGrid size={17} /><FileText size={17} /><CalendarDays size={17} /><span className="m-demo-avatar">D</span></aside>
    <div className="m-demo-body"><div className="m-demo-top"><span><span className="m-app-icon">d</span> Daylight <ChevronDown size={12} /></span><span className="m-demo-sample">Sample product <span>·</span> Interactive preview</span><span className="m-demo-context"><Search size={14} /> Product workspace</span></div>
      <div className="m-demo-heading"><div><p className="m-label">YOUR NEXT MOVE</p><h2>{tab === "calendar" ? "Make room for the next moment." : tab === "localization" ? "Same meaning. New markets." : "Make a stronger first impression."}</h2></div><span className="m-pill"><span /> In progress</span></div>
      <div className="m-demo-tabs" role="tablist" aria-label="Explore the sample workspace">{tabs.map(({ id, label, icon: Icon }, index) => <button key={id} id={`demo-tab-${id}`} ref={el => { buttons.current[index] = el; }} role="tab" aria-selected={tab === id} aria-controls={`demo-panel-${id}`} tabIndex={tab === id ? 0 : -1} onClick={() => setTab(id)} onKeyDown={event => {
        const next = event.key === "ArrowRight" ? (index + 1) % tabs.length : event.key === "ArrowLeft" ? (index + tabs.length - 1) % tabs.length : event.key === "Home" ? 0 : event.key === "End" ? tabs.length - 1 : -1;
        if (next >= 0) { event.preventDefault(); setTab(tabs[next].id); buttons.current[next]?.focus(); }
      }}><Icon size={14} />{label}</button>)}</div>
      <div className="m-demo-panel" id={`demo-panel-${tab}`} role="tabpanel" aria-labelledby={`demo-tab-${tab}`} tabIndex={0}>
        {tab === "listing" && <div className="m-demo-listing"><div className="m-demo-editor"><div className="m-editor-title"><strong>Google Play listing</strong><span>en-US <ChevronDown size={11} /></span></div><div className="m-demo-field"><span>App title <small>22 / 30</small></span><p>Daylight: Daily Habits</p></div><div className="m-demo-field"><span>Short description <small>67 / 80</small></span><p>Build small routines and make room for a little progress every day.</p></div><div className="m-demo-field m-demo-long"><span>Full description</span><p>A little progress, every day.</p><p>Choose a habit. Find your rhythm. Daylight helps you build a daily routine, one small step at a time.</p></div><div className="m-demo-editor-footer"><span><Check size={12} /> Editable draft</span><span>Review before publishing</span></div></div><aside className="m-demo-insight"><span className="m-insight-icon"><Sparkles size={18} /></span><p className="m-label">THE THINKING BEHIND IT</p><h3>Lead with the everyday benefit.</h3><p>“Small routines” makes the experience feel approachable. Keep that promise consistent with your first screenshot.</p><div className="m-demo-source"><CircleCheck size={14} /><span>Based on product context<br /><small>Sample recommendation</small></span></div><div className="m-demo-next"><span>UP NEXT</span><strong>Review your source copy <ArrowUpRight size={14} /></strong></div></aside></div>}
        {tab === "localization" && <div className="m-demo-locales"><div className="m-locale-source"><span className="m-pill"><Check size={12} /> Source copy approved</span><h3>Daylight: Daily Habits</h3><p>One source listing. A thoughtful adaptation for every locale.</p></div><div className="m-locale-table">{[["EN", "English (US)", "Source listing", "Approved"], ["ES", "Spanish (Spain)", "Daylight: Hábitos diarios", "Needs review"], ["DE", "German", "Daylight: Tägliche Routinen", "Draft"], ["FR", "French", "Daylight : habitudes", "Draft"]].map(([code, language, title, status]) => <div key={code}><span className="m-locale-code">{code}</span><strong>{language}<small>{title}</small></strong><span className="m-locale-status">{status}</span></div>)}</div><p className="m-demo-note">Illustrative translations. Every locale needs language and factual review.</p></div>}
        {tab === "calendar" && <div className="m-demo-calendar"><div className="m-calendar-title"><h3>A week with a plan.</h3><span>Daylight · Sample week</span></div><div className="m-calendar-days">{["MON", "TUE", "WED", "THU", "FRI"].map((day, i) => <div key={day}><small>{day}</small><strong>{12 + i}</strong></div>)}</div><div className="m-calendar-events"><div className="m-cal-event m-cal-green"><span>PRODUCT MOMENT</span><strong>Build a morning routine</strong><small>Monday–Thursday · In-app event</small></div><div className="m-cal-event m-cal-peach"><span>STORE UPDATE</span><strong>New screenshot story</strong><small>Wednesday · Creative review</small></div><div className="m-cal-event m-cal-purple"><span>LOCALIZATION</span><strong>Spanish listing review</strong><small>Thursday–Friday · Review</small></div></div><p className="m-demo-note">Sample planning calendar. Promotional events are submitted in Play Console.</p></div>}
      </div>
    </div>
  </div><div className="m-demo-caption"><span><span className="m-live-dot" /> Explore the preview tabs</span><span>Illustrative workspace · No account needed</span></div></div>;
}
