export const SITE_URL = "https://sort3d.space";
export const CONTENT_DATE = "2026-10-08";

export const features = [
  {
    slug: "google-play-aso", eyebrow: "GOOGLE PLAY ASO", title: "Give your store listing a clearer story.",
    seoTitle: "Google Play ASO Tool for Apps & Games",
    description: "Research, draft, and review Google Play store listings with Sorted. Keep app context, ASO recommendations, and publishing in one product workspace.",
    intro: "Turn what makes your app useful into a listing people can understand. Sorted keeps research, current metadata, and your next draft together, so every edit has a reason.",
    steps: [
      ["Start with the actual product", "Add your app or game, review the imported details, and capture its audience and positioning. When a public listing cannot be imported, you can enter and correct the details yourself."],
      ["Develop a focused listing", "Use your research to draft a title, short description, and full description. AI recommendations are starting points to evaluate against the app, not evidence of search volume or a guaranteed ranking."],
      ["Review, then send", "Edit the copy, check the field limits, and compare it with your current listing. With a supported Google Play connection and appropriate permissions, explicitly send your selected listing changes to Google Play."],
    ],
    takeaway: "One product. One source of context. A listing you can explain.",
    faqs: [
      ["Does Sorted track keyword search volume or rank positions?", "Sorted provides product research, AI-assisted recommendations, and listing workflows. It does not currently provide a verified keyword-volume database or continuous store-rank tracking. Treat generated keyword ideas as hypotheses to validate."],
      ["Will an ASO edit guarantee more installs?", "No. Discovery and conversion depend on your app, audience, competition, creative assets, product quality, and distribution. Record a baseline, make a focused change, and evaluate comparable data over time."],
      ["Can I publish my Google Play listing from Sorted?", "Connected, authorized accounts can send supported listing text and selected locales to Google Play after review. Google permissions, review, and publishing settings still determine when changes become visible."],
    ], guide: "google-play-aso-checklist", preview: "listing" as const,
  },
  {
    slug: "app-localization", eyebrow: "APP STORE LOCALIZATION", title: "A familiar product. In their language.",
    seoTitle: "Google Play Listing Localization Tool",
    description: "Localize Google Play listings from your approved source copy. Review AI translations, check character limits, and publish selected locales with Sorted.",
    intro: "Build on the listing you already approved. Sorted gives each locale its own editable title and descriptions, with the same product context behind every draft.",
    steps: [
      ["Agree on your source copy", "Finish the main listing first. Keep feature names, product claims, and audience assumptions clear before creating localized drafts. Updating the source calls for another review of existing translations."],
      ["Adapt each market", "Generate locale-specific drafts, then review terminology, tone, and field lengths. Prioritize markets where the app can support users, and ask a fluent reviewer to check important translations."],
      ["Publish the locales you approve", "Save your changes and select the locales you want to send through the Google Play connection. Plan localized screenshots and the in-app experience alongside the listing text."],
    ],
    takeaway: "Carry the meaning across markets. Keep the final say.",
    faqs: [
      ["Does Sorted translate the app itself?", "The localization workflow covers store listing text. Translating your in-app interface, support material, screenshots, or legal content remains separate work."],
      ["Are AI translations ready to publish without review?", "No. Check the language, factual claims, brand names, and field lengths in every locale. Native or fluent review is especially useful for your highest-priority markets."],
      ["Which locales should I start with?", "Choose using your audience, existing traffic, product availability, and support capacity. A popular language worldwide is not automatically the best next market for a particular app."],
    ], guide: "localize-google-play-listing", preview: "localization" as const,
  },
  {
    slug: "promotional-content", eyebrow: "PROMOTIONAL CONTENT & EVENTS", title: "Give every product moment a plan.",
    seoTitle: "Google Play Promotional Content & Event Planning",
    description: "Plan Google Play promotional content with a product calendar, editable event copy, creative briefs, and review workflows in Sorted.",
    intro: "A new season, feature launch, or in-game event deserves more than a last-minute document. Put the dates, message, and creative work in the same product workspace.",
    steps: [
      ["Put the moment on the calendar", "Plan events for a specific app or game, with a start date, end date, and event type. Use the product calendar for focused planning and the portfolio view to keep multiple products in view."],
      ["Prepare the package", "Draft an event message and creative brief using your product context. Review the offer, destination, eligibility, artwork, and timing together before marking work ready."],
      ["Hand off and learn", "Submit promotional content through Play Console. Where report access is configured, review available promotional observations in Sorted. Observed changes alone do not prove that an event caused a lift."],
    ],
    takeaway: "A calendar that connects the date to the work behind it.",
    faqs: [
      ["Can Sorted publish promotional events directly to Google Play?", "Not currently. Sorted helps plan and prepare promotional content; event submission and approval take place in Play Console. Direct listing-text publishing is a separate supported workflow."],
      ["Can every developer use Google Play promotional content?", "Access and event eligibility depend on Google Play's current requirements and the app's account. Check availability and content requirements in Play Console before planning a submission."],
      ["Does each product have its own calendar?", "Yes. Calendar planning is tied to an individual product, with a portfolio view for coordinating work across products."],
    ], guide: "promotional-content-planning", preview: "calendar" as const,
  },
];

export const guides = [
  {
    slug: "google-play-aso-checklist", category: "ASO FOUNDATIONS", title: "A practical Google Play ASO checklist", minutes: "6 min read",
    description: "A repeatable Google Play ASO workflow: establish a baseline, improve listing copy, align screenshots, and measure the next change.",
    answer: "Start with an accurate product promise, a relevant audience, and a recorded baseline. Improve one clear part of the listing, review the text and creative assets together, then compare equivalent periods and audiences. ASO is an ongoing product decision, not a one-time keyword exercise.",
    sections: [
      { id: "baseline", title: "1. Save the listing you have today", paragraphs: ["Capture the current title, descriptions, icon, screenshots, locale, and publication date. Write down the app version and any active campaigns. Without that context, it is easy to mistake a paid campaign, product release, or seasonal change for the effect of new copy.", "Keep measures separate: people reaching a listing, people taking the next action, and people who remain active in the app answer different questions. Use the definitions shown in your report and compare the same source, country, and date range. Mark unavailable data as missing; a missing observation is not zero."], checklist: ["Save the current listing and locale.", "Record traffic sources, dates, and concurrent campaigns.", "Choose the outcome you want to learn about before editing."] },
      { id: "intent", title: "2. Write for one recognizable need", paragraphs: ["Describe the job your app helps someone do, in language they would use themselves. A habit app could focus on building a simple daily routine; a puzzle game could lead with short, satisfying sessions. These are editorial examples, not measured keyword opportunities.", "Build candidate phrases from support conversations, user research, and the product itself. Review competitor listings to understand how the category communicates, but do not copy their claims. Ask whether every promise remains true after someone installs. AI can suggest wording; it cannot turn an unsupported claim into a fact."] },
      { id: "fields", title: "3. Give each text field a distinct job", paragraphs: ["Google Play allows up to 30 characters for an app name, 80 for a short description, and 4,000 for a full description. Treat these as ceilings, not writing targets. The short description should add a reason to care, while the full description can explain the experience in a useful order.", "For a fictional habit app named Daylight, a title such as ‘Daylight: Daily Habits’ identifies the category. A short description such as ‘Build small routines and make room for a little progress every day.’ adds a benefit. The full description should then show how the routine works, which features exist, and who the app is for."], checklist: ["Check every field with the listing checker.", "Remove filler, repeated phrases, and unverified superlatives.", "Keep feature and pricing claims accurate to the app."] },
      { id: "creative", title: "4. Make the screenshots support the promise", paragraphs: ["Treat the first screenshots as a sequence: the user need, the product experience, and the result the user can reasonably expect. Show the actual app or game. A short headline above a readable interface usually explains more than a crowded list of features.", "Check the sequence on a phone-sized screen. Make sure the store copy, screenshots, and first-use experience tell a consistent story. If the listing promises simplicity but the screenshots are dense, revise the presentation before trying more keywords."] },
      { id: "review", title: "5. Review and publish deliberately", paragraphs: ["Name the specific hypothesis behind the change. For example: ‘Explaining the daily reminder in the first screenshot will make the routine easier to understand.’ Review factual accuracy, policy requirements, locale, and final artwork together. Where suitable, use a controlled store listing experiment instead of relying only on before-and-after observations.", "Keep a record of what changed and when it actually went live. Decide in advance which result would justify keeping, revising, or reverting the change. Avoid declaring a winner from a small or mismatched sample. The most useful outcome can be a clearer question for the next iteration."] },
    ],
    sources: [{ label: "Google Play: store listing fields and limits", url: "https://support.google.com/googleplay/android-developer/answer/9859152?hl=en" }, { label: "Google Play: store listing best practices", url: "https://support.google.com/googleplay/android-developer/answer/13393723?hl=en" }], feature: "google-play-aso",
  },
  {
    slug: "localize-google-play-listing", category: "LOCALIZATION", title: "How to localize a Google Play listing", minutes: "5 min read",
    description: "Choose the right locales, build a translation brief, review localized app listing copy, and measure each Google Play market separately.",
    answer: "Approve the source listing first, choose markets your product can support, and adapt the message for each locale. Check terminology and character limits, review localized creative assets, then publish selected locales and monitor them separately. Translation is only one part of localization.",
    sections: [
      { id: "markets", title: "1. Choose markets with a reason", paragraphs: ["A universal top-ten language list is a useful brainstorming prompt, not a market strategy. Start with countries and languages already appearing in your product data, support requests, or research. Consider the usefulness of your app in each market, relevant regulations, payment availability, and the languages your team can support.", "A simple prioritization note is enough: audience evidence, product readiness, reviewer availability, and the cost of maintaining the locale. Launch a manageable first group. A carefully maintained locale is more useful than ten translations that drift away from the product."], checklist: ["Record the evidence behind each target locale.", "Confirm that the product works for that market.", "Find someone who can review the language."] },
      { id: "source", title: "2. Freeze a source version and glossary", paragraphs: ["Finish your primary listing before creating translations. Identify brand names that must stay unchanged, feature names that must match the interface, and claims that need exact wording. Add a short audience note and explain the intended tone with examples.", "Save the source version and date beside the localized draft. If the source changes later, mark translations for review. Reusing approved source copy prevents each language from quietly becoming a different product promise."] },
      { id: "adapt", title: "3. Adapt meaning before compressing text", paragraphs: ["A literal translation can be grammatically correct and still sound unnatural. Ask the reviewer whether a local user would understand the value, recognize the category, and trust the wording. Idioms, humor, and urgency deserve special attention; they rarely travel unchanged.", "Review each title and description against the store's field limits. When a translation is too long, rewrite the sentence around its main idea. Truncating the last characters can remove the qualification or benefit that makes the message accurate. Keep a separate review of spelling, punctuation, and product claims."] },
      { id: "assets", title: "4. Review the complete local experience", paragraphs: ["Google Play lets developers add localized listing text and visual assets. Check screenshots with embedded words as carefully as the descriptions. Dates, numbers, text direction, and interface labels should make sense together.", "Listing localization does not translate your app's interface. Tell reviewers which languages the product itself supports, and make sure the store experience does not imply support that does not exist. Open the destination links and check the first-use journey as part of review."], checklist: ["Review title, short description, and full description.", "Check screenshot language and text legibility.", "Verify that support and destination links are usable."] },
      { id: "learn", title: "5. Publish a reviewed set and keep learning", paragraphs: ["Keep locale approval explicit. Record the exact language code, source version, reviewer, and publication date, then send only the locales you approved. Check the published result rather than assuming a successful request means the listing is already visible.", "Review each market using comparable traffic and reporting definitions. A change in traffic mix can alter conversion without saying anything about translation quality. Keep language feedback alongside the numbers so the next revision addresses a real question."] },
    ], sources: [{ label: "Google Play: translation and localization", url: "https://support.google.com/googleplay/android-developer/answer/9844778?hl=en" }, { label: "Google Play: listing field limits", url: "https://support.google.com/googleplay/android-developer/answer/9859152?hl=en" }], feature: "app-localization",
  },
  {
    slug: "promotional-content-planning", category: "PROMOTIONAL CONTENT", title: "Plan a Google Play promotional content event", minutes: "5 min read",
    description: "Build an event brief for Google Play promotional content with dates, audience, eligibility, creative assets, review steps, and measurement.",
    answer: "Begin with a real product moment and check promotional content access in Play Console. Define the audience, offer or experience, dates, destination, copy, and assets in one brief. Review eligibility and content requirements before submitting, then use the available reports to learn from the event.",
    sections: [
      { id: "moment", title: "1. Choose a moment worth returning for", paragraphs: ["Start with something that is actually happening inside the app or game: a feature release, a seasonal experience, or an event. Write the user-facing reason in one sentence. If the only reason is ‘we need a campaign this week,’ the product moment may need more work.", "Separate a content idea from an approved event. Google Play controls access, eligibility, and review. Verify those details in your own Play Console before promising that a campaign can appear on the store. An entry in a planning calendar is not a Google Play submission."], checklist: ["Confirm the experience exists and will be ready.", "Check promotional content access in Play Console.", "Identify a specific intended audience."] },
      { id: "brief", title: "2. Write one brief everyone can use", paragraphs: ["Keep the product, event type, start and end dates, time zone, audience, destination, headline, message, and asset requirements together. Name the person responsible for reviewing the copy and the person responsible for the in-app experience.", "For a fictional puzzle game's seasonal challenge, explain how players enter, what changes during the event, and what happens after it ends. If there is an offer, be precise about availability and conditions. The copy should help a player decide whether the event is relevant without needing a second explanation."] },
      { id: "calendar", title: "3. Plan backwards from the start date", paragraphs: ["Use separate milestones for product readiness, draft review, asset delivery, submission, and launch. Leave room for revision rather than scheduling the first review on launch day. The amount of lead time depends on your team and the store's current review process.", "Keep each app's events in its own calendar so names and dates retain their context. Use a combined portfolio view to spot overlapping launches or review bottlenecks. A schedule is useful when it exposes the work that still needs an owner, not just the final date."] },
      { id: "handoff", title: "4. Review the experience behind the artwork", paragraphs: ["Read the event copy next to the final artwork and the destination screen. Confirm that a user who taps can reach the promised content and understand any conditions. Check the correct build, regions, language, availability window, and eligible audience.", "Submit the reviewed event in Play Console and track its actual status there. Sorted supports planning and preparation; direct promotional event submission is not currently part of its Google Play integration. Keep that distinction visible in your team's process."], checklist: ["Test the destination on a real device.", "Review claims, artwork, and audience restrictions.", "Record the submission status and final live dates."] },
      { id: "measurement", title: "5. Separate observations from conclusions", paragraphs: ["Save the available event reporting with the event brief. Use the metric definitions provided by the source, including date ranges and whether a figure is daily or rolling. Do not add overlapping rolling windows and describe the result as unique people.", "An increase during an event is an observation, not proof of causation. Releases, paid campaigns, seasonality, and traffic mix can change the same measures. Write a short retrospective: what launched, what was observed, what remains uncertain, and what you would change next time."] },
    ], sources: [{ label: "Google Play: promotional content quality guidelines", url: "https://support.google.com/googleplay/android-developer/answer/12929944?hl=en" }], feature: "promotional-content",
  },
];

export const publicPaths = ["/", ...features.map(f => `/features/${f.slug}`), "/integrations/google-play", "/guides", ...guides.map(g => `/guides/${g.slug}`), "/tools/google-play-listing-checker", "/about", "/pricing", "/contact"];

export const homeFaqs = [
  ["What is Sorted?", "Sorted (at sort3d.space) is an organic growth workspace for mobile app and game teams. It connects product research, Google Play app store optimization (ASO), listing localization, promotional planning, and performance review."],
  ["Who is it built for?", "Independent developers, mobile game teams, and app growth teams who want product context, drafts, and launch plans in one place. Each product has its own workspace, with a portfolio view across products."],
  ["What does the Google Play connection do?", "Authorized accounts can synchronize supported listing information and send reviewed listing text and selected locales to Google Play. Available quality and promotional reporting depend on the permissions and report access configured for the product."],
  ["Does Sorted automatically publish AI-generated content?", "No. Generated copy stays editable and needs your review. Listing publishing is an explicit action; promotional event submission currently happens in Play Console."],
  ["Can Sorted guarantee rankings or AI search mentions?", "No. Sorted helps organize research and improve the work behind organic growth. Store rankings, search visibility, and AI search citations depend on many factors beyond any one tool."],
];
